version: '3'
services:
  api: 
    image: node:16-alpine 
    working_dir: '/home/node/app'
    command: ['npm', 'run', 'start:dev']
    ports: 
      - '4000:4000'
    volumes:
      - './api:/home/node/app'
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    restart: always 
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: myuser
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuser
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
    driver: local